<?php
/**
 * List of supported languages for Google Translate
 */

function sgt_get_supported_languages() {
    return array(
        'af' => array('name' => 'Afrikaans', 'flag' => 'za'),
        'sq' => array('name' => 'Albanian', 'flag' => 'al'),
        'am' => array('name' => 'Amharic', 'flag' => 'et'),
        'ar' => array('name' => 'Arabic', 'flag' => 'sa'),
        'hy' => array('name' => 'Armenian', 'flag' => 'am'),
        'az' => array('name' => 'Azerbaijani', 'flag' => 'az'),
        'eu' => array('name' => 'Basque', 'flag' => 'es'),
        'be' => array('name' => 'Belarusian', 'flag' => 'by'),
        'bn' => array('name' => 'Bengali', 'flag' => 'bd'),
        'bs' => array('name' => 'Bosnian', 'flag' => 'ba'),
        'bg' => array('name' => 'Bulgarian', 'flag' => 'bg'),
        'ca' => array('name' => 'Catalan', 'flag' => 'es'),
        'ceb' => array('name' => 'Cebuano', 'flag' => 'ph'),
        'zh-CN' => array('name' => 'Chinese (Simplified)', 'flag' => 'cn'),
        'zh-TW' => array('name' => 'Chinese (Traditional)', 'flag' => 'tw'),
        'co' => array('name' => 'Corsican', 'flag' => 'fr'),
        'hr' => array('name' => 'Croatian', 'flag' => 'hr'),
        'cs' => array('name' => 'Czech', 'flag' => 'cz'),
        'da' => array('name' => 'Danish', 'flag' => 'dk'),
        'nl' => array('name' => 'Dutch', 'flag' => 'nl'),
        'en' => array('name' => 'English', 'flag' => 'gb'),
        'eo' => array('name' => 'Esperanto', 'flag' => 'eu'),
        'et' => array('name' => 'Estonian', 'flag' => 'ee'),
        'fi' => array('name' => 'Finnish', 'flag' => 'fi'),
        'fr' => array('name' => 'French', 'flag' => 'fr'),
        'fy' => array('name' => 'Frisian', 'flag' => 'nl'),
        'gl' => array('name' => 'Galician', 'flag' => 'es'),
        'ka' => array('name' => 'Georgian', 'flag' => 'ge'),
        'de' => array('name' => 'German', 'flag' => 'de'),
        'el' => array('name' => 'Greek', 'flag' => 'gr'),
        'gu' => array('name' => 'Gujarati', 'flag' => 'in'),
        'ht' => array('name' => 'Haitian Creole', 'flag' => 'ht'),
        'ha' => array('name' => 'Hausa', 'flag' => 'ng'),
        'haw' => array('name' => 'Hawaiian', 'flag' => 'us'),
        'he' => array('name' => 'Hebrew', 'flag' => 'il'),
        'hi' => array('name' => 'Hindi', 'flag' => 'in'),
        'hmn' => array('name' => 'Hmong', 'flag' => 'cn'),
        'hu' => array('name' => 'Hungarian', 'flag' => 'hu'),
        'is' => array('name' => 'Icelandic', 'flag' => 'is'),
        'ig' => array('name' => 'Igbo', 'flag' => 'ng'),
        'id' => array('name' => 'Indonesian', 'flag' => 'id'),
        'ga' => array('name' => 'Irish', 'flag' => 'ie'),
        'it' => array('name' => 'Italian', 'flag' => 'it'),
        'ja' => array('name' => 'Japanese', 'flag' => 'jp'),
        'jv' => array('name' => 'Javanese', 'flag' => 'id'),
        'kn' => array('name' => 'Kannada', 'flag' => 'in'),
        'kk' => array('name' => 'Kazakh', 'flag' => 'kz'),
        'km' => array('name' => 'Khmer', 'flag' => 'kh'),
        'rw' => array('name' => 'Kinyarwanda', 'flag' => 'rw'),
        'ko' => array('name' => 'Korean', 'flag' => 'kr'),
        'ku' => array('name' => 'Kurdish', 'flag' => 'iq'),
        'ky' => array('name' => 'Kyrgyz', 'flag' => 'kg'),
        'lo' => array('name' => 'Lao', 'flag' => 'la'),
        'la' => array('name' => 'Latin', 'flag' => 'va'),
        'lv' => array('name' => 'Latvian', 'flag' => 'lv'),
        'lt' => array('name' => 'Lithuanian', 'flag' => 'lt'),
        'lb' => array('name' => 'Luxembourgish', 'flag' => 'lu'),
        'mk' => array('name' => 'Macedonian', 'flag' => 'mk'),
        'mg' => array('name' => 'Malagasy', 'flag' => 'mg'),
        'ms' => array('name' => 'Malay', 'flag' => 'my'),
        'ml' => array('name' => 'Malayalam', 'flag' => 'in'),
        'mt' => array('name' => 'Maltese', 'flag' => 'mt'),
        'mi' => array('name' => 'Maori', 'flag' => 'nz'),
        'mr' => array('name' => 'Marathi', 'flag' => 'in'),
        'mn' => array('name' => 'Mongolian', 'flag' => 'mn'),
        'my' => array('name' => 'Myanmar (Burmese)', 'flag' => 'mm'),
        'ne' => array('name' => 'Nepali', 'flag' => 'np'),
        'no' => array('name' => 'Norwegian', 'flag' => 'no'),
        'ny' => array('name' => 'Nyanja (Chichewa)', 'flag' => 'mw'),
        'or' => array('name' => 'Odia (Oriya)', 'flag' => 'in'),
        'ps' => array('name' => 'Pashto', 'flag' => 'af'),
        'fa' => array('name' => 'Persian', 'flag' => 'ir'),
        'pl' => array('name' => 'Polish', 'flag' => 'pl'),
        'pt' => array('name' => 'Portuguese', 'flag' => 'pt'),
        'pa' => array('name' => 'Punjabi', 'flag' => 'in'),
        'ro' => array('name' => 'Romanian', 'flag' => 'ro'),
        'ru' => array('name' => 'Russian', 'flag' => 'ru'),
        'sm' => array('name' => 'Samoan', 'flag' => 'ws'),
        'gd' => array('name' => 'Scots Gaelic', 'flag' => 'gb'),
        'sr' => array('name' => 'Serbian', 'flag' => 'rs'),
        'st' => array('name' => 'Sesotho', 'flag' => 'ls'),
        'sn' => array('name' => 'Shona', 'flag' => 'zw'),
        'sd' => array('name' => 'Sindhi', 'flag' => 'pk'),
        'si' => array('name' => 'Sinhala (Sinhalese)', 'flag' => 'lk'),
        'sk' => array('name' => 'Slovak', 'flag' => 'sk'),
        'sl' => array('name' => 'Slovenian', 'flag' => 'si'),
        'so' => array('name' => 'Somali', 'flag' => 'so'),
        'es' => array('name' => 'Spanish', 'flag' => 'es'),
        'su' => array('name' => 'Sundanese', 'flag' => 'id'),
        'sw' => array('name' => 'Swahili', 'flag' => 'tz'),
        'sv' => array('name' => 'Swedish', 'flag' => 'se'),
        'tl' => array('name' => 'Tagalog (Filipino)', 'flag' => 'ph'),
        'tg' => array('name' => 'Tajik', 'flag' => 'tj'),
        'ta' => array('name' => 'Tamil', 'flag' => 'in'),
        'tt' => array('name' => 'Tatar', 'flag' => 'ru'),
        'te' => array('name' => 'Telugu', 'flag' => 'in'),
        'th' => array('name' => 'Thai', 'flag' => 'th'),
        'tr' => array('name' => 'Turkish', 'flag' => 'tr'),
        'tk' => array('name' => 'Turkmen', 'flag' => 'tm'),
        'uk' => array('name' => 'Ukrainian', 'flag' => 'ua'),
        'ur' => array('name' => 'Urdu', 'flag' => 'pk'),
        'ug' => array('name' => 'Uyghur', 'flag' => 'cn'),
        'uz' => array('name' => 'Uzbek', 'flag' => 'uz'),
        'vi' => array('name' => 'Vietnamese', 'flag' => 'vn'),
        'cy' => array('name' => 'Welsh', 'flag' => 'gb'),
        'xh' => array('name' => 'Xhosa', 'flag' => 'za'),
        'yi' => array('name' => 'Yiddish', 'flag' => 'il'),
        'yo' => array('name' => 'Yoruba', 'flag' => 'ng'),
        'zu' => array('name' => 'Zulu', 'flag' => 'za')
    );
}
